---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cli-mcp.redhat.com
  resources:
  - climcpinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cli-mcp.redhat.com
  resources:
  - climcpinstances/finalizers
  verbs:
  - update
- apiGroups:
  - cli-mcp.redhat.com
  resources:
  - climcpinstances/status
  verbs:
  - get
  - patch
  - update
